input:
  sheets:
    - ALL尺码匹配
    - TM尺码匹配
    - HNT尺码匹配

columns:
  品牌:
    - MAKE
    - 品牌
  前台车型:
    - MODEL
    - 前台车型
  结构:
    - 结构
  版本:
    - 版本
  年份区间:
    - YEAR
    - 年份区间
  最终尺码:
    - 确认尺码
    - 自动尺码
    - 最终尺码
    - 对应尺码
  驾驶室类型:
    - CAB
    - 驾驶室类型
  货斗长度_ft:
    - BED
    - 货斗长度_ft
  子车系:
    - SUB-MODEL
    - 子车系
  分类:
    - 分类

defaults:
  分类: ""
